// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// AdminChat represents a row from 'public.admin_chat'.
type AdminChat struct {
	ID     int   `db:"id" json:"id"`           // id
	ChatID int64 `db:"chat_id" json:"chat_id"` // chat_id
}

// zeroAdminChat zero value of dto
var zeroAdminChat = AdminChat{}

func (t AdminChat) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroAdminChat)
}
