// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// AdminMessage represents a row from 'public.admin_messages'.
type AdminMessage struct {
	ID         int    `db:"id" json:"id"`                   // id
	ScenarioID int64  `db:"scenario_id" json:"scenario_id"` // scenario_id
	Step       int    `db:"step" json:"step"`               // step
	Message    string `db:"message" json:"message"`         // message
}

// zeroAdminMessage zero value of dto
var zeroAdminMessage = AdminMessage{}

func (t AdminMessage) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroAdminMessage)
}
