// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// ContentType represents a row from 'public.content_types'.
type ContentType struct {
	ID   int            `db:"id" json:"id"`     // id
	Name sql.NullString `db:"name" json:"name"` // name
}

// zeroContentType zero value of dto
var zeroContentType = ContentType{}

func (t ContentType) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroContentType)
}
