// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// Content represents a row from 'public.contents'.
type Content struct {
	ID            int    `db:"id" json:"id"`                           // id
	ScenarioID    int    `db:"scenario_id" json:"scenario_id"`         // scenario_id
	StepID        int    `db:"step_id" json:"step_id"`                 // step_id
	MediaTgID     string `db:"media_tg_id" json:"media_tg_id"`         // media_tg_id
	ContentTypeID int    `db:"content_type_id" json:"content_type_id"` // content_type_id
}

// zeroContent zero value of dto
var zeroContent = Content{}

func (t Content) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroContent)
}
