// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// DoctorMessage represents a row from 'public.doctor_messages'.
type DoctorMessage struct {
	ID         int    `db:"id" json:"id"`                   // id
	ScenarioID int64  `db:"scenario_id" json:"scenario_id"` // scenario_id
	Step       int    `db:"step" json:"step"`               // step
	Message    string `db:"message" json:"message"`         // message
}

// zeroDoctorMessage zero value of dto
var zeroDoctorMessage = DoctorMessage{}

func (t DoctorMessage) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroDoctorMessage)
}
