// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// Doctor represents a row from 'public.doctors'.
type Doctor struct {
	ID         int          `db:"id" json:"id"`                   // id
	TgID       int64        `db:"tg_id" json:"tg_id"`             // tg_id
	FullName   string       `db:"full_name" json:"full_name"`     // full_name
	TgUsername string       `db:"tg_username" json:"tg_username"` // tg_username
	IsActive   sql.NullBool `db:"is_active" json:"is_active"`     // is_active
}

// zeroDoctor zero value of dto
var zeroDoctor = Doctor{}

func (t Doctor) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroDoctor)
}
