// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"reflect"

	"github.com/lib/pq"
)

// DoctorsScenario represents a row from 'public.doctors_scenarios'.
type DoctorsScenario struct {
	ID          int         `db:"id" json:"id"`                     // id
	DoctorID    int         `db:"doctor_id" json:"doctor_id"`       // doctor_id
	ScenarioID  int         `db:"scenario_id" json:"scenario_id"`   // scenario_id
	Step        int         `db:"step" json:"step"`                 // step
	CompletedAt pq.NullTime `db:"completed_at" json:"completed_at"` // completed_at
}

// zeroDoctorsScenario zero value of dto
var zeroDoctorsScenario = DoctorsScenario{}

func (t DoctorsScenario) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroDoctorsScenario)
}
