// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// InformationPost represents a row from 'public.information_posts'.
type InformationPost struct {
	ID            int64          `db:"id" json:"id"`                           // id
	Name          string         `db:"name" json:"name"`                       // name
	PostsThemeID  int64          `db:"posts_theme_id" json:"posts_theme_id"`   // posts_theme_id
	OrderInTheme  int            `db:"order_in_theme" json:"order_in_theme"`   // order_in_theme
	MediaID       sql.NullString `db:"media_id" json:"media_id"`               // media_id
	ContentTypeID sql.NullInt64  `db:"content_type_id" json:"content_type_id"` // content_type_id
	PostText      string         `db:"post_text" json:"post_text"`             // post_text
}

// zeroInformationPost zero value of dto
var zeroInformationPost = InformationPost{}

func (t InformationPost) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroInformationPost)
}
