// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
	"time"

	"github.com/lib/pq"
)

// Newsletter represents a row from 'public.newsletters'.
type Newsletter struct {
	ID              int64           `db:"id" json:"id"`                             // id
	RecipientsCount sql.NullInt64   `db:"recipients_count" json:"recipients_count"` // recipients_count
	Text            string          `db:"text" json:"text"`                         // text
	UsersLists      []sql.NullInt64 `db:"users_lists" json:"users_lists"`           // users_lists
	UsersIds        []sql.NullInt64 `db:"users_ids" json:"users_ids"`               // users_ids
	MediaID         sql.NullString  `db:"media_id" json:"media_id"`                 // media_id
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`             // created_at
	SentAt          pq.NullTime     `db:"sent_at" json:"sent_at"`                   // sent_at
	Name            sql.NullString  `db:"name" json:"name"`                         // name
	StatusID        sql.NullInt64   `db:"status_id" json:"status_id"`               // status_id
	ContentTypeID   sql.NullInt64   `db:"content_type_id" json:"content_type_id"`   // content_type_id
}

// zeroNewsletter zero value of dto
var zeroNewsletter = Newsletter{}

func (t Newsletter) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroNewsletter)
}
