// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// NewslettersStatus represents a row from 'public.newsletters_status'.
type NewslettersStatus struct {
	ID   int64  `db:"id" json:"id"`     // id
	Name string `db:"name" json:"name"` // name
}

// zeroNewslettersStatus zero value of dto
var zeroNewslettersStatus = NewslettersStatus{}

func (t NewslettersStatus) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroNewslettersStatus)
}
