// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"

	"github.com/lib/pq"
)

// PatientPost represents a row from 'public.patient_posts'.
type PatientPost struct {
	ID         int64        `db:"id" json:"id"`                   // id
	PatientID  int64        `db:"patient_id" json:"patient_id"`   // patient_id
	PostID     int64        `db:"post_id" json:"post_id"`         // post_id
	IsReceived sql.NullBool `db:"is_received" json:"is_received"` // is_received
	SentTime   pq.NullTime  `db:"sent_time" json:"sent_time"`     // sent_time
}

// zeroPatientPost zero value of dto
var zeroPatientPost = PatientPost{}

func (t PatientPost) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroPatientPost)
}
