// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"reflect"
	"time"
)

// PatientStepAnswer represents a row from 'public.patient_step_answers'.
type PatientStepAnswer struct {
	ID         int       `db:"id" json:"id"`                   // id
	PatientID  int       `db:"patient_id" json:"patient_id"`   // patient_id
	ScenarioID int       `db:"scenario_id" json:"scenario_id"` // scenario_id
	StepID     int       `db:"step_id" json:"step_id"`         // step_id
	AnswerText string    `db:"answer_text" json:"answer_text"` // answer_text
	AnswerDate time.Time `db:"answer_date" json:"answer_date"` // answer_date
}

// zeroPatientStepAnswer zero value of dto
var zeroPatientStepAnswer = PatientStepAnswer{}

func (t PatientStepAnswer) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroPatientStepAnswer)
}
