// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// PostsTheme represents a row from 'public.posts_themes'.
type PostsTheme struct {
	ID         int64        `db:"id" json:"id"`                   // id
	Name       string       `db:"name" json:"name"`               // name
	IsRequired sql.NullBool `db:"is_required" json:"is_required"` // is_required
}

// zeroPostsTheme zero value of dto
var zeroPostsTheme = PostsTheme{}

func (t PostsTheme) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroPostsTheme)
}
