// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
	"time"
)

// Scenario represents a row from 'public.scenarios'.
type Scenario struct {
	ID          int            `db:"id" json:"id"`                   // id
	Name        string         `db:"name" json:"name"`               // name
	Description sql.NullString `db:"description" json:"description"` // description
	IsActive    sql.NullBool   `db:"is_active" json:"is_active"`     // is_active
	Delay       *time.Duration `db:"delay" json:"delay"`             // delay
}

// zeroScenario zero value of dto
var zeroScenario = Scenario{}

func (t Scenario) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroScenario)
}
