// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// StepButton represents a row from 'public.step_buttons'.
type StepButton struct {
	ID            int           `db:"id" json:"id"`                           // id
	Scenario      int           `db:"scenario" json:"scenario"`               // scenario
	Step          int           `db:"step" json:"step"`                       // step
	ButtonText    string        `db:"button_text" json:"button_text"`         // button_text
	NextStepOrder sql.NullInt64 `db:"next_step_order" json:"next_step_order"` // next_step_order
}

// zeroStepButton zero value of dto
var zeroStepButton = StepButton{}

func (t StepButton) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroStepButton)
}
