// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import "reflect"

// UserList represents a row from 'public.user_lists'.
type UserList struct {
	ID   int64  `db:"id" json:"id"`     // id
	Name string `db:"name" json:"name"` // name
}

// zeroUserList zero value of dto
var zeroUserList = UserList{}

func (t UserList) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroUserList)
}
