// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"database/sql"
	"reflect"
)

// UsersList represents a row from 'public.users_lists'.
type UsersList struct {
	ID     int64         `db:"id" json:"id"`           // id
	UserID sql.NullInt64 `db:"user_id" json:"user_id"` // user_id
	ListID sql.NullInt64 `db:"list_id" json:"list_id"` // list_id
}

// zeroUsersList zero value of dto
var zeroUsersList = UsersList{}

func (t UsersList) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroUsersList)
}
